apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "dev"

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "dev"

  role: "KarpenterNodeRole-dev"

  # renovate: datasource=aws-machine-image
  # amiFilter=[{"Name":"owner-id","Values":["602401143452"]},{"Name":"name","Values":["amazon-eks-node-al2023-x86_64-standard-1.32-*"]},{"region":"eu-west-1"}]
  amiSelectorTerms:
    - id: ami-0eea2e74caa3766a7

  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required

  # Optional, configures storage devices for the instance
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        encrypted: false
        deleteOnTermination: true
# aws ec2 describe-images --filters Name=owner-id,Values=602401143452 Name=name,Values=amazon-eks-node-al2023-x86_64-standard-1.32-* --region eu-west-1 --query Images[*].Name | sort
